name: status_hub
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # UI & Design
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.1.0
  cached_network_image: ^3.3.1

  # Media & Stickers
  giphy_get: ^3.0.3 # GIPHY integration
  image_picker: ^1.1.2

  # Sharing & Saving
  share_plus: ^9.0.0
  saver_gallery: ^3.0.6
  permission_handler: ^11.3.1

  # Storage (trending templates, user prefs)
  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking (fetch trending templates)
  http: ^1.2.1
  dio: ^5.5.0

  # Utils
  uuid: ^4.4.0
  path_provider: ^2.1.3
  flutter_animate: ^4.5.0 # smooth animations
  smart_date_formatter: ^0.0.4
  firebase_core: ^3.4.0
  firebase_remote_config: ^5.1.0
  cloud_firestore: ^5.4.0
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/status_hub_app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "assets/icons/status_hub_app_icon.png"

flutter_native_splash:
  color: "#6C63FF"
  color_dark: "#4B44CC"
  image: assets/icons/status_hub_app_icon.png
  image_dark: assets/icons/status_hub_app_icon.png
  branding: assets/icons/background.png
  android_12:
    image: assets/icons/status_hub_app_icon.png
    icon_background_color: "#6C63FF"
    icon_background_color_dark: "#4B44CC"
  fullscreen: true
  android: true
  ios: true
